version: '3.8'

services:
  study-app:
    build: .
    container_name: study-app
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql-study
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study_tracker
      MYSQL_USER: study
      MYSQL_PASSWORD: study
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-study
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-study
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge